module.exports = () => {
  const colors = [
    'firebrick',
    'crimson',
    'darkred',
    'mediumVioletRed',
    'deeppink',
    'tomato',
    'orangered',
    'darkorange',
    'orange',
    'coral',
    'gold',
    'darkkhaki',
    'orchid',
    'rebeccapurple',
    'darkmagenta',
    'slateblue',
    'indigo',
    'limegreen',
    'mediumseagreen',
    'green',
    'olive',
    'darkcyan',
    'darkturqoise',
    'steelblue',
    'dodgerblue',
    'deepskyblue',
    'mediumblue',
    'goldenrod',
    'saddlebrown',
    'brown',
    'maroon',
    'dimgray',
    'darkslategray',
    'black',
    
  ]
  return colors[Math.floor(Math.random() * colors.length)];
}